### ISSUE TITLE
Tab titles are unreadable when hovered over

### ISSUE THREAD

**Issue by onetom** [snowe2010/solarized-jetbrains#10]
When the Version Control / Log tab is selected and I hover over the Console tab, it's gray on dark brown, which is unreadable.

It's not a big problem, since you won't stay in such state for long, but still a slight dirty spot on the otherwise super-pleasing design :)

Also, the inactive editor tabs look more prominent than the selected one, but that could be just me...
I normally limit my tab count to 1 and just use Cmd-E to navigate my open files exclusively from keyboard, by fuzzy searching their name or by Ctrl-Tab to switch between the recent 2 files, so it's not a big issue for me personally.

**Comment by snowe2010** [comment]
How do you feel about this?

Unfocused:

<img width="188" alt="Screen Shot 2019-09-17 at 3 12 32 PM" src="https://user-images.githubusercontent.com/1534535/65080052-a7af9a00-d95d-11e9-83a0-a08b02a7404a.png">

Focused:

<img width="194" alt="Screen Shot 2019-09-17 at 3 12 39 PM" src="https://user-images.githubusercontent.com/1534535/65080081-b5651f80-d95d-11e9-93ce-287b72de5a43.png">


I also released a new version today, 3.0.0, which should be up in the plugin repository in a few days after they review it. Could you check that one out and see if it fixes the inactive editor tab looks for you?

**Comment by snowe2010** [comment]
Hi @onetom, I'm going to close this issue as resolved, since the above change was released in version 3.0.0. If you don't like the end result, go ahead and reopen this issue and let me know what you think would be better.
