### ISSUE TITLE
Flat design

### ISSUE THREAD

**Issue by bartkummel** [snowe2010/solarized-jetbrains#12]
I don't like the lines in the solarized dark theme. I think a flat design, such as in the "dark flat" theme gives a more modern look.

Solarized dark theme:
![Schermafbeelding 2019-07-12 om 14 12 53](https://user-images.githubusercontent.com/20771942/61127530-cef67080-a4af-11e9-957c-300773abe975.png)

Dark Flat theme:
![Schermafbeelding 2019-07-12 om 14 13 10](https://user-images.githubusercontent.com/20771942/61127542-d61d7e80-a4af-11e9-969c-8a535dd67bcd.png)

**Comment by snowe2010** [comment]
Hi @bartkummel, the newest version of Solarized Theme should follow a more modern style, fixed in #15.
