### ISSUE TITLE
Some directories are not readable

### ISSUE THREAD

**Issue by tenhobi** [snowe2010/solarized-jetbrains#2]
For me, `cmake-build-debug` directory has a really poor contrast and is not readable.

![image](https://user-images.githubusercontent.com/5287596/54535482-ece31700-498e-11e9-859f-60543346def3.png)

**Comment by tofagerl** [comment]
Same, I'm back to Darcula in order to actually work, and I am sad...

**Comment by ayzenquwe** [comment]
<img width="216" alt="Screen Shot 2019-03-19 at 3 12 41 PM" src="https://user-images.githubusercontent.com/4571520/54608660-db1a7600-4a59-11e9-9111-c1d83af814f6.png">

Same for me: various items have a very strange contrast.
I think those panels should be lighter.

**Comment by sonOfRa** [comment]
Yep, test source and test resources are also almost impossible to read in java-projects:
![color-problems](https://user-images.githubusercontent.com/1269520/55394369-770aae00-553f-11e9-8a4c-cadcda557ee0.png)

**Comment by sungkang** [comment]
I had the exact same issue with the highlighting. A workaround is to clone the project, run the makefile, and prepare the project for deployment. Then I just deleted the plugin and added it manually. That did the trick.

**Comment by arm-liang** [comment]
It could  be worse . I even  can't  recognize the class name in the tab bar or popup list,
especially in the tab item .
![W6G)P2 1I@(Y9YXX5{PV}RF](https://user-images.githubusercontent.com/37470680/62546021-552a8a80-b895-11e9-8c80-3d97d7f62f69.png)

**Comment by snowe2010** [comment]
Hi, I'm sorry for the delay. Apparently I wasn't signed up for notifications for my own repository somehow. These issues should have been fixed quite a long time ago, but I've released a new version (3.0.0) which should be approved by JetBrains in a few days so if you don't mind, please try updating now or then and it should be fixed.

**Comment by snowe2010** [comment]
The new version is released, please let me know if you are still seeing issues!

**Comment by sungkang** [comment]
Thanks for the update! I’ll check shortly.

**Comment by arm-liang** [comment]
thanks for update，i will update soon.

**Comment by sonOfRa** [comment]
Looks pretty good now, contrasts are much improved. Thank you!

**Comment by sonOfRa** [comment]
The only slight issue I have is confirmation dialogs like this one:
![window](https://user-images.githubusercontent.com/1269520/65524838-cd551a00-deee-11e9-923e-8634beb1828d.png)

The colors seem a bit off (same thing also happens in the solarized light theme)

![window2](https://user-images.githubusercontent.com/1269520/65524951-fecde580-deee-11e9-84eb-7707596e39cc.png)

**Comment by snowe2010** [comment]
@sonOfRa Good find, could you open up a new issue for this and I'll close this one as done? I can fix that in the next version.
