### ISSUE TITLE
method parameter tips and cvs log have low contrast

### ISSUE THREAD

**Issue by arm-liang** [snowe2010/solarized-jetbrains#24]
System envirnoment: Win10 1809, Intellij Idea 2019.2, 3.0 solarized theme.
Issue: The method parameter tips's constrast is very low.(WebStrom dosen't have that issue) 
![O__RHINMZ8`%4O0P6E}01X6](https://user-images.githubusercontent.com/37470680/67387866-461cc400-f5ca-11e9-9e53-f1376ae5d68d.png)

And the background of CVS log is incompatible with the surroundings.(WebStrom and Idea is same)
![7KR2VSW_2DNL}4JR6HU9S4N](https://user-images.githubusercontent.com/37470680/67387939-677db000-f5ca-11e9-885d-b316279b64e9.png)

**Comment by snowe2010** [comment]
Second issue is documented in #9. Could you take a look over there and let me know what you think of those colors? I'll look into fixing the first issue.

**Comment by snowe2010** [comment]
@arm-liang what do you think about #25 which will fix your first issue? I've put screenshots in there showing what it would look like.

**Comment by arm-liang** [comment]
I'm sorry. I didn't know the problem was there.It's my first to add issue.

I think the cvs log panel's color might be like with the surroundings. At leateast in my view, the dark color is unfriendly. The background color same as editor is ok.(Forgive my poor English)

**Comment by snowe2010** [comment]
Sorry for the delay in response, so did #25 look like a good solution to you?
