### ISSUE TITLE
Code peek has incorrect color

### ISSUE THREAD

**Issue by arm-liang** [snowe2010/solarized-jetbrains#26]
![image](https://user-images.githubusercontent.com/37470680/68355348-ed146a80-0149-11ea-9505-ce0c67db65b4.png)

The **code suggest** in the code peek of WebStrom has incorrect color as same as the previous version 2.0's default editor color. 
Envirnoment: 
Latest Theme 3.0
Win10 1809
WebStrom 2019.2.3

**Comment by snowe2010** [comment]
What do you think about this? 

![Screen Shot 2019-12-11 at 4 19 40 PM](https://user-images.githubusercontent.com/1534535/70668887-15ecbb80-1c32-11ea-833e-569d6d718320.png)
![Screen Shot 2019-12-11 at 4 19 25 PM](https://user-images.githubusercontent.com/1534535/70668888-15ecbb80-1c32-11ea-962d-b82b39188445.png)

**Comment by arm-liang** [comment]
It is ok.
Thanks.
