### ISSUE TITLE
Lines between menu and toolbar, tab lines are too bright (dark theme)

### ISSUE THREAD

**Issue by GoldenEagle19** [snowe2010/solarized-jetbrains#6]
First of all, thank for such an amazing theme. I wanted to get IntelliJ  IDEA to look like this for so long. You made it possible. Thank you.
2 things I would like to improve (I'm talking about dark version here)
1. The white line between the menu and the toolbar is too bright. I think it's kind of distracting and hard too look at.
2. Same goes for the tabs framing.

I think it would be great if these lines are changed to some dark color or at least not so white. Example of possible color: line between toolbar and folder structure bar.

Thanks in advance.

**Comment by snowe2010** [comment]
Hi @GoldenEagle19, sorry for the massive delay in response. Apparently Github decided I didn't want notifications for my own repositories. Could you take a picture of what you are talking about?
