### ISSUE TITLE
Currently active file selection is visible only when sidebar has focus

### ISSUE THREAD

**Issue by brokenthorn** [snowe2010/solarized-jetbrains#7]
### Problem
When using Autoscroll from source, you are supposed to see which file you are editing in the sidebar, but the _"selected"_ background effect is only visible when the sidebar is focused. Clicking on the sidebar titlebar gives it focus and only then is the selected file visible.

#### Unfocused sidebar:
![image](https://user-images.githubusercontent.com/2119004/57480699-222e2600-72a9-11e9-8e33-c2441ef50d03.png)

#### Focused sidebar after clicking the sidebar titlebar:
![image](https://user-images.githubusercontent.com/2119004/57480736-37a35000-72a9-11e9-899d-c93c2892d599.png)

**Comment by BrannonKing** [comment]
This too has been affecting me. I often use the right-click in the project panel, which action then hides the selection.

**Comment by toterGott** [comment]
Affected me too

**Comment by snowe2010** [comment]
Hi, this should have been fixed in the most recent version. 3.0.0. It will be up as soon as JetBrains approves it. 

Closed in #13
